language: generic
sudo: false

env:
  - EVM_EMACS=emacs-26.1-travis
  - EVM_EMACS=emacs-git-snapshot-travis

matrix:
  fast_finish: true
  allow_failures:
    - env: EVM_EMACS=emacs-git-snapshot-travis

before_install:
  - if [ ! -z "$EVM_EMACS" ]; then curl -fsSkL https://gist.github.com/rejeep/ebcd57c3af83b049833b/raw > x.sh && source ./x.sh; fi
  - if [ ! -z "$EVM_EMACS" ]; then evm install $EVM_EMACS --use --skip; fi

script:
  - emacs --version
  - cd ~/.emacs.d
  - emacs --batch -l init.el -f batch-byte-compile init.el