language: generic

sudo: false

addons:
  apt:
    sources:
    - cassou-emacs
    packages:
    - emacs26

env:
  matrix:
    - EMACS=emacs26
    - EMACS=emacs-snapshot

install:
  - brew install emacs

script:
  - emacs --version

notifications:
  email: false

# Local variables:
# coding: utf-8
# End:
