language: emacs-lisp
sudo: required

env:
  - EVM_EMACS=emacs-26.1-travis

before_install:
  - mv -f ../.emacs.d ~/.emacs.d
  - curl -fsSkL https://gist.github.com/rejeep/ebcd57c3af83b049833b/raw > x.sh && source ./x.sh
  - evm install $EVM_EMACS --use --skip

script:
  - emacs --version
  - cd ~/.emacs.d
  - emacs --batch -l init.el -f batch-byte-compile init.el