language: generic
sudo: false
dist: trusty
os:
  - osx
env:
  - EVM_EMACS=emacs-26.1-travis
before_install:
  - git clone https://github.com/rejeep/evm.git $HOME/.evm
  - export PATH="$HOME/.evm/bin:$PATH"
  - evm config path /tmp
  - evm install $EVM_EMACS --use
script:
  - emacs --version
